apiVersion: v1
kind: Service
metadata:
  name: helm-web-api-service
spec:
  selector:
    app: helm-web-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 4000
    protocol: TCP
