# Default values for on-demand-micro-services-deployment-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # uncomment and fill registry name
  registry: harbor.sausmpc01.pcf.dell.com
  name: platform_eng_public/helm-web-api
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 4000

namespace: helm-api

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: helm-api
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: tiller-user
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system
