apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.helmServiceAccount }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.helmRole }}
  namespace: {{ .Values.rbac.tillerNamespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.tillerRoleBindingName }}
  namespace: {{ .Values.rbac.tillerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.helmRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.helmServiceAccount }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "on-demand-micro-services-deployment-k8s.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "on-demand-micro-services-deployment-k8s.name" . }}
    chart: {{ template "on-demand-micro-services-deployment-k8s.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "on-demand-micro-services-deployment-k8s.name" . }}
    release: {{ .Release.Name }}